### ISSUE TITLE
BUG: All 'normal' value warped to '400'

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#12]
Basically
white-space:normal;
font-style:normal;

All these values get transformed to '400'

I assume that your code just assumes normal only applies to 'font-weight' where normal can equate to 400, otherwise it breaks other things that use that value.

**Comment by Omniferum** [comment]
Excellent script by the way. I should PROBABLY have started with that.

**Comment by cassiobotaro** [comment]
will be fixed in #13.

**Comment by juancarlospaco** [comment]
Thanks @Omniferum and @cassiobotaro :grey_exclamation: 

d-( ʘ‿ʘ )_m
==========
