### ISSUE TITLE
CSS rule reordering

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#14]
CSS Rules get reordered, however whether or not this is a true concern for you I'm unsure.

Example:
    margin: 0 auto;
    margin-bottom: 1%;
Transforms to:
    margin-bottom: 1%;
    margin: 0 auto;

So obviously the margin-bottom becomes redundant with the new ordering.

**Comment by juancarlospaco** [comment]
I think we should have a flag for Skip reordering, just like we have the `--obfuscate` on JS.

Thanks for the Contributions @Omniferum we need to detect and improve more stuff :smile_cat:

**Comment by Omniferum** [comment]
Unsure if there is a need to reorder the CSS at all.

Given it is a 'cascade' and that fiddling with the order does not result in any gzip/compression benefit (I think) it seems to serve no purpose. Does it alphabetize it?

However if I am wrong on that point, all we need to do is ensure specificity is ordered top-down. So all broad descriptors go on the top and the more specific ones go on the bottom.

Margin: 0 auto;
Margin-bottom: 10px;
Margin-top: 1%;

Etc.

All specifics are hypenated anyway so you can just edit the .py to output those at the end of the css class it belongs to.

If we are going to enforce it though I would prefer alphabetizing it so everything stays grouped together and just add the hyphen rule.

On 16 June 2015 18:29:21 GMT+08:00, Juan Carlos <notifications@github.com> wrote:
>I think we should have a flag for Skip reordering, just like we have
>the `--obfuscate` on JS.
>
>Thanks for the Contributions @Omniferum we need to detect and improve
>more stuff :smile_cat: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/juancarlospaco/css-html-js-minify/issues/14#issuecomment-112378567

-- 
Sent from my Android device, please excuse my brevity.

**Comment by juancarlospaco** [comment]
It alphabetizes. Thats kind of a Best Practice.
It help spotting cloned attributes on the CSS rules.

The idea now is to make it optional.
