### ISSUE TITLE
Windows: ImportError: No module named '_curses'

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#15]
I'm aware the curses module is a unix thing, however in the previous commit I wasn't getting this error.

Not a coder and all I can report that nothing in my environment has changed. Simply replace css-html-js-minify.py with the one from the new commit and bang, ImportError: No module named '_curses'.

**Comment by juancarlospaco** [comment]
Fixed, thanks :grey_exclamation:
