### ISSUE TITLE
Windows 'same directory' error

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#18]
In the readme it does say:
fullpath         Full path to local file or folder.

But for morons like myself it might be good to print out the error:
"You didn't give me a full path to work with!"

Or something to that effect.

**Comment by juancarlospaco** [comment]
![io_error](https://cloud.githubusercontent.com/assets/1189414/8208440/09fca4e4-14de-11e5-8c05-4949c0219622.jpg)

**File or folder not found,or cant be read,or I/O Error.**

On Blinking Red, on platforms that support 256 colors on terminals.

¯|_(ツ)/¯

**Comment by Omniferum** [comment]
Run from a cmd.exe window

INPUT: c:\Python34\python.exe css-html-js-minify.py 1.css

OUTPUT: 
Creating Abstract UDP Socket Lock for Single Instance.
Socket Lock for Single Instance: <socket.socket fd=524, family=AddressFamily.AF_
INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888)>.
CSS-HTML-JS-Minify.

StandAlone Async single-file cross-platform no-dependencies
Unicode-ready Python3-ready Minifier for the Web.
1.0.14
STDOUT Encoding: cp437.
STDIN Encoding: cp437.
STDERR Encoding: cp437.
Default Encoding: utf-8.
FileSystem Encoding: mbcs.
PYTHONIOENCODING Encoding: None.
Checking the Working Folder: .
Folder  does not exist !.
Traceback (most recent call last):
  File "css-html-js-minify.py", line 1269, in <module>
    main()
  File "css-html-js-minify.py", line 1225, in main
    check_working_folder(os.path.dirname(args.fullpath))
  File "css-html-js-minify.py", line 1081, in check_working_folder
    hdd = int(disk_usage(folder_to_check).free / 1024 / 1024 / 1024)
  File "c:\Python34\lib\shutil.py", line 989, in disk_usage
    total, free = nt._getdiskusage(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified

----------------------------

The documentation states that a 'full path' is required, but I can use relative directories. So it seems like the only check if there is a slash in the path or not.

INPUT: c:\Python34\python.exe css-html-js-minify.py test\1.css

OUTPUT: normal

So a full path is not a strict requirement as such.

However just for win it doesn't quite output the error. There should be spaces after the commas in the error message though (just me and grammar).

**Comment by juancarlospaco** [comment]
- Full path is not a strict requirement as such.
- Full path is recommended.
- Documentation always try to recommend the recommended.

Yes, sometimes I omit space after comma on error messages, 
is to respect the 80 characters per line that Python has as best practice *(A.K.A. PEP8)*

:)

**Comment by Omniferum** [comment]
I can accept that people would rarely be using the python script and .css in the exact same folder so happy to conclude this as a fringe case, but I would assume most windows users would execute this from a command window (cmd.exe) and what it outputs as an error is confusing is all.

I'm speaking more from the perspective of a non-coder and someone that just tries his best to bash tools together to make them work, so things like Tracebacks and anything further might put off some others. I guess it depends on what sort of accessibility you want the script to have. In my mind it would make sense to add a check if path contains no slash then:
os.path.abspath(os.path.dirname(sys.argv[0]))

Or whatever would fetch the current working directory and check if the file is in the same dir.

Alternatively
Checking the Working Folder: .
Folder  does not exist !.

If Working folder = '.' then print "You provided no folder path!" instead of the !.

But really this is far more up to you than anything else. I'm just offering a perspective.

**Comment by juancarlospaco** [comment]
I am using the python script and .css in the exact same folder, and it works just ok.

```
cd ~/code/css-html-js-minify/
python3 css-html-js-minify.py file.css
python3 css-html-js-minify.py ~/code/css-html-js-minify/file.css
```

I'm interested in more perspective of a non-coder, let me check if there is something we can do to make that more human.

On Linux/Mac the `.` IS a valid folder, maybe not on Windows, because it cant find it, but still.
Basically, on MS Window sometimes paths fail if they are not full path, sadly, nothing we can do.

Thats great feedbacks :+1:

**Comment by juancarlospaco** [comment]
Ok, so I am creating a new Logger/Debugger/Friendly-Printer for this, so far looks like this:

```python
juan@z:~$ python3 /home/juan/recipe.py

Traceback (most recent call last):
  File "/home/juan/recipe.py", line 105, in <module>
    pad4(data)
  File "/home/juan/recipe.py", line 97, in pad4
    return_value.append("0" * (4 - len(thing)) + thing)
TypeError: object of type 'int' has no len()
########################## D E B U G #########################
Listing all Locals by context frame,ordered by innermost last:

The Function pad4() from file /home/juan/recipe.py at line 97 failed!.
     Function pad4()
    |
    |__ return_value = ['0001', '0002']  # Type: <class 'list'>
    |__ seq = ['1', '2', 3, '4']  # Type: <class 'list'>
    |__ thing = 3  # Type: <class 'int'>

 Thats all we know about the error, check the LOG file.
 ########################## D E B U G #########################
juan@z:~/Downloads$
```

It will only appear on critical errors and tracebacks, will have 256 Colors on OS that support it.
`/home/juan/recipe.py` is just a dumb file that fails for no reason just to show the error description.

Definitely more friendly to copy-paste on a Bug Report...

:bulb:
