### ISSUE TITLE
Running from windows error with commit 082aa4976d

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#19]
WARNING:root:Unix SysLog Server not found,ignored Logging to SysLog.
Unix SysLog Server not found,ignored Logging to SysLog.

**Comment by juancarlospaco** [comment]
Ok, i changed the "severity" of the message from `warning` to `debug` but I think it should remain,
it says `SysLog Server not found` its clear and simple that theres no SysLog server running,
SysLog is a centralized standard built-in Log system on Linux/Os X/BSD and others, 
theres also third party compatible Win32 implementations *(i know nothing about that)*.

Thanks for the Contributions :grey_exclamation:
