### ISSUE TITLE
Inserting ; after inline comment

### ISSUE THREAD

**Issue by harrysouthworth** [juancarlospaco/css-html-js-minify#22]
Thanks for making this available.

I'm chaining commands like this (D3):
```javascript
svg.append("line")
     .attr("x1", xScale(stats.x))
     .attr("x2", xScale(stats.x))
```

If I stick a comment in between two lines, minifying causes a ; to be inserted where the comment was:
```javascript
svg.append("line")
     // Putting a comment here is ok by every browser I've tried, so maybe it's legal
     .attr("x1", xScale(stats.x))
     .attr("x2", xScale(stats.x))
```

Thanks,
Harry

**Comment by juancarlospaco** [comment]
- This looks like kind of Corner Case.
- Thats sure not Best Practice IMHO.

*...but still a Valid Bug.*


You can also do stuff like:
```javascript
.attr("x1" /* foo */ , xScale( /* bar */ stats.x) /* annoying to parse */ )
```
And still will work on the browser probably...  :sob: 

We try to Minify *"Written in Good Intentions"* JavaScript, with nice Style Guides, not Fix or Un-Obfuscate JavaScript.

*...but still a Valid Bug.*
