### ISSUE TITLE
unquote_html_attributes breaks with XHTML-style closed tags

### ISSUE THREAD

**Issue by ShadowNinja** [juancarlospaco/css-html-js-minify#28]
A tag like `<img src="abc.xyz"/>` will be transformed to `<img src=abc.xyz/>` --- which breaks the image since `abc.xyz/` is a  link to a directory.
This would also break any other atributes that can be unquoted, are the last in their tag, and are in an XHTML-style closed tag.

**Comment by juancarlospaco** [comment]
Unquote html attributes is not meant for XHTML style of syntax, but for HTML5 style of syntax.

I understand the bug anyways.

**Comment by cassiobotaro** [comment]
maybe a xtml flag?

**Comment by juancarlospaco** [comment]
I dont see too much people really using XHTML, on real life, every day use, on production.

I think just probably fixing the Bug in first place will be enough, add a white space there should fix it.

:ghost:

**Comment by ShadowNinja** [comment]
I found this issue while minifying the output of Doxygen.  So yes, it's used in production.
