### ISSUE TITLE
Please fill in description and url on pypi is wrong

### ISSUE THREAD

**Issue by lowks** [juancarlospaco/css-html-js-minify#3]
Hi I found two issues:

1. There is no description for your project so it's described as `UNKNOWN` on `pypi`
2. The url link you provided does not come back to your github space for this project. You can just leave the ticks `'` out of your url in pypi. The reason why it's not coming back to your github page is because of the ticks. 

Perhaps it would be good if you created your `setup.py` ?

**Comment by juancarlospaco** [comment]
Hello @lowks !!!, thanks for using the App :smile_cat: 

I just uploaded it, like right now... I got some problems with the PyPI server today...

Been trying to Upload the Wheel to PyPI but it keeps failing.

```shell
Server response (500): Internal Server Error
```
 or

```shell
Upload failed (400): Binary wheel for an unsupported platform
```

Already got the setup.py and the wheel on my local to install, but PyPI fails.

I have Fixed the Bad Ticks !, it should work, it works for me here.

The Setup.py is here: https://github.com/juancarlospaco/css-html-js-minify/blob/master/setup.py

the RestructuredText gets all garbled, unreadable, so I just post the link there to the README here.
see here for example is not rendering ok: https://pypi.python.org/pypi/octopussh

Any Improvement, Fix, Idea, Comment, etc etc feel Free to make a Bug or Pull Request !

:sob:
