### ISSUE TITLE
Unable to use python code for 1.2.2; couldn't install current version from github

### ISSUE THREAD

**Issue by germn** [juancarlospaco/css-html-js-minify#33]
I installed css-html-js-minify with pip and tried to use as module

> from css_html_js_minify import js_minify

but it didn't work: 

> No module named 'css_html_js_minify'

Then, I tried to install package from git directly with following command:

> pip install https://github.com/juancarlospaco/css-html-js-minify/zipball/master

But got no success:

> Command "python setup.py egg_info" failed with error code 1 in C:\Users\\...\AppData\Local\Temp\\...

Windows 10, Python 3.5

Is there any plans to update PyPi version?
Is there any way to install current version from github?

**Comment by juancarlospaco** [comment]
- Version 1.2.2 can not be used as a module.
- Live code from Git may or may not be stable.
- There are plans to update PyPi version, when Master is ready.
- PyPi version is recent, less than 6month old.
- Master version is recent, less than 1month old.

:smile_cat:
