### ISSUE TITLE
Output cuts off after minimization

### ISSUE THREAD

**Issue by valsr** [juancarlospaco/css-html-js-minify#35]
Minimizing some js scripts (jQuery) leads to prematurely truncating the file producing an incorrectly minimized script. I have attached both the original code and the minified version.
[jquery.js.txt](https://github.com/juancarlospaco/css-html-js-minify/files/311020/jquery.js.txt)
[jquery.min.js.txt](https://github.com/juancarlospaco/css-html-js-minify/files/311019/jquery.min.js.txt)
[css-html-js-minify.log.txt](https://github.com/juancarlospaco/css-html-js-minify/files/311023/css-html-js-minify.log.txt)

Here is the console output:
Unix SysLog Server trying to Log to SysLog: /dev/log 
Logger created with Log file at: /tmp/css-html-js-minify.log. 
\x1B]0; css-html-js-minify \x07
Python 3.4.3 on Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa. 
STDIN Encoding: UTF-8. 
STDERR Encoding: UTF-8. 
STDOUT Encoding:UTF-8 
Default Encoding: utf-8. 
FileSystem Encoding: utf-8. 
PYTHONIOENCODING Encoding: None. 
Process Name set to: css-html-js-minify. 
Creating Abstract UDP Socket Lock for Single Instance. 
Socket Lock for Single Instance: <socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=b'\x00_css-html-js-minify__lock'>. 
Max Logging ON 
CSS-HTML-JS-Minify.

Minifier for the Web.
2.0.0 
Checking the Working Folder: '/work/themer/build/cake/modern/js/modern' 
Folder Total Free Space: ~503 GigaBytes. 
Beep sound at exit OFF 
Target is a JS File. 
Processing JS file: jquery.js. 
INPUT: Reading JS file jquery.js. 
Force remove commented out lines from Javascript. 
Compressing Javascript... 
Forcing JS from ~1 to 1 Line. 
Prepending '.MIN.JS' Prefix to jquery.js. 
OUTPUT: Writing JS Minified jquery.min.js. 

---

 Files Processed: jquery.js. 
Number of Files Processed: 1. 
\x1B]0;\x07
Total Maximum RAM Memory used: 68 of 12005MegaBytes.
Total Working Time: ~ 0:00:00.103668.

Compressing Old Rotated Logs on ZIP file

: /tmp/css-html-js-minify.logs-old.zip 
File Name                                             Modified             Size

**Comment by spotke** [comment]
It seems related to inline comments. Here is a minimal example to reproduce:
OK:
`// log to console
console.log('hello world!');
OTHER CODE HERE`

Cuts off right after the first statement:
`console.log('hello world!'); // logs to console
OTHER CODE HERE`

**Comment by juancarlospaco** [comment]
Please see: https://github.com/juancarlospaco/css-html-js-minify#javascript-support

Feel free to send Pull Requests, thanks...
