### ISSUE TITLE
subprocess.getoutput deprecated

### ISSUE THREAD

**Issue by mverleg** [juancarlospaco/css-html-js-minify#39]
Using the latest (469688b3f07c8a9f1f2713c76433130c0191fbe1) version and using ``Python 2.7.11+``, I get this eror:

    Traceback (most recent call last):
      File "css-html-js-minify.py", line 11, in <module>
        from css_html_js_minify.minify import prepare, main
      File "css_html_js_minify/__init__.py", line 11, in <module>
        from .minify import (process_single_html_file, process_single_js_file,
      File "/css_html_js_minify/minify.py", line 21, in <module>
        from subprocess import getoutput
    ImportError: cannot import name getoutput

Should not be hard to [fix](http://stackoverflow.com/questions/6657690/python-getoutput-equivalent-in-subprocess).

**Comment by romanseidl** [comment]
This is NOT fixed. Ther commit is not in this repo and not in pip etc.

**Comment by juancarlospaco** [comment]
We are not supporting Python 2 anymore.
