### ISSUE TITLE
Issue with pip?

### ISSUE THREAD

**Issue by cuducos** [juancarlospaco/css-html-js-minify#4]
Hola Juan! Thanks for this script, looks really interesting :)

I'm trying to install it via `pip` but got the following error:

```
Downloading/unpacking css-html-js-minify==1.0.6
  Downloading css-html-js-minify-1.0.6.tar.gz
  Running setup.py (path:/home/cuducos/.virtualenvs/test/build/css-html-js-minify/setup.py) egg_info for package css-html-js-minify
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/cuducos/.virtualenvs/test/build/css-html-js-minify/setup.py", line 51, in <module>
        long_description=github_markdown_to_restructuredtext(),
      File "/home/cuducos/.virtualenvs/test/build/css-html-js-minify/setup.py", line 39, in github_markdown_to_restructuredtext
        with open(filename) as github_markdown:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/cuducos/.virtualenvs/test/build/css-html-js-minify/setup.py", line 51, in <module>

    long_description=github_markdown_to_restructuredtext(),

  File "/home/cuducos/.virtualenvs/test/build/css-html-js-minify/setup.py", line 39, in github_markdown_to_restructuredtext

    with open(filename) as github_markdown:

FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

I thought I could just fix whatever is wrong but it looks like the version being served from PyPI doesn't match the current `master` branch here — so maybe you're working in the next version, and maybe already aware of this error. But anyway, just reporting and trying to help.

Looks like it's a simple issue, so if you fixed it already for the next version, it's great. Otherwise let me know and I'll try to sort it out and send a PR.

Muchas gracias

**Comment by juancarlospaco** [comment]
Version `1.0.9` should Fix this.

I got some weird problems with PyPI Project Description, 
since it does not Render my `*.rst` RestructuredText,
so I choose to Upload it without Long Description, they should support `*.md` Markdown...

Builds and Tests are Passing Ok on Travis-CI. Some new Features added.

:smile:

**Comment by cuducos** [comment]
Hell yeah! Gracias, Juan – just installed it here :)

**Comment by juancarlospaco** [comment]
Bien, cualquier otro Bicho o Idea es bienvenido.

He agregado que Travis-CI lo instale via PIP tambien, asi no falla mas.

:rabbit:
