### ISSUE TITLE
Why lost double quotes?

### ISSUE THREAD

**Issue by jbiWeisendorf** [juancarlospaco/css-html-js-minify#41]
Today I used the first time html minify
After minify (html) meta charset = "UTF-8"  to meta charset = utf-8 double quotes are no longer present!

Who can explain the reason.

Thank you very much
Jürgen Bierlein

**Comment by juancarlospaco** [comment]
Because they are not needed at all.
They are fully optional, and will be added client-side anyways.
https://mothereff.in/unquoted-attributes

**Comment by jbiWeisendorf** [comment]
now; i got 244 Linter Problems from the Interactive Linter in brackets and i need two files 
1) my org file
2) the minify one

**Comment by juancarlospaco** [comment]
Report a Bug on the Interactive Linter in brackets.

Minified files may not always pass all code style checkers anyways.

**Comment by juancarlospaco** [comment]
d-( ʘ‿ʘ )_m
