### ISSUE TITLE
Explicit grant of license in the work

### ISSUE THREAD

**Issue by bignose-debian** [juancarlospaco/css-html-js-minify#47]
The text in the Read Me document suggests a license name, but does not explicitly grant license to the recipient. Without that, a cautious reader will not know exactly whether they have any license to do anything with the work.

The GNU GPL text has a section “How to Apply These Terms […]” which describes how to make an explicit grant of license in the work.

**Comment by bignose-debian** [comment]
My suggested implementation to resolve this is in the branch at https://git.fosscommunity.in/bignose/css-html-js-minify/tree/wip/issue/license-grant in my personal fork.

**Comment by mverleg** [comment]
Hmm the document you mention indeed describes a more elaborate procedure than is being used. I have no legal experience, so my opinion isn't worth much here. But writing a several lines notice in the readme or, as described in the document, in every source file, sounds over-done for a simple project with no serious legal interests worth protecting.

Personally I'd just follow the steps on http://choosealicense.com/ .

> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders. 

Those perhaps aren't really directed at cautious readers. But let's be honest, you have to be a little bit paranoid to expect to be successfully sued for assuming this project is available under GPL license.

**Comment by juancarlospaco** [comment]
I agree with @mverleg 
Licence on every file is too much noise. 
Will make a review over the weekend anyways...
Keep it simple

**Comment by bignose-debian** [comment]
> Hmm the document you mention indeed describes a more elaborate procedure than is being used.

Yes. I am not advocating to modify every file; just one, the top-level Read Me document.

> Keep it simple

Agreed. What is needed is an explicit grant of license; one place, the Read Me document is simple for that. Please reconsider the change I proposed, to make an explicit grant of license in the work.

**Comment by juancarlospaco** [comment]
Thanks...
