### ISSUE TITLE
Install the named command-line program via Setuptools

### ISSUE THREAD

**Issue by bignose-debian** [juancarlospaco/css-html-js-minify#48]
Setuptools has a feature named ‘entry_points’ that allows [automating the creation of commands](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) available to run as a separate program.

This is the recommended way to configure the application's command-line program: define a function to call, and configure Setuptools for the distribution so that the named command invokes that function.

**Comment by bignose-debian** [comment]
My suggested implementation of this improvement is in the branch at https://git.fosscommunity.in/bignose/css-html-js-minify/tree/wip/feature/command-entry-point in my personal fork.

This entails re-working the mainline code so that it is encapsulated in an application class, and a conventional ‘main’ function for the program module.

**Comment by mverleg** [comment]
Sounds like a good approach. It would be somewhat more convenient to have a pull request though, it's a bit harder to compare/merge the specifics now...

**Comment by juancarlospaco** [comment]
LGTM.
But can be more convenient to have a pull request for it.
