### ISSUE TITLE
Correct the distribution description

### ISSUE THREAD

**Issue by bignose-debian** [juancarlospaco/css-html-js-minify#49]
The distribution description (defined in Distutils ‘setup.py’) describes the distribution inaccurately; there are modifiers that are not true.

In particular, the program is not single-file, and the distribution does have dependencies.

**Comment by bignose-debian** [comment]
My proposed implementation to resolve this issue is in the branch at https://git.fosscommunity.in/bignose/css-html-js-minify/tree/wip/issue/correct-description in my personal fork repository.

**Comment by juancarlospaco** [comment]
True, it started as single-file, but then community wanted to be more modular and reusable.
