### ISSUE TITLE
Unnecessary spaces between tags and at the end of tags

### ISSUE THREAD

**Issue by davidtgq** [juancarlospaco/css-html-js-minify#54]
1. Between every tag, there is a space:

`<!DOCTYPE html> <title>foobar</title> <meta charset=utf-8/> <meta name=viewport content="width=device-width, initial-scale=1">`

It should be like [html-minifier's](https://kangax.github.io/html-minifier/) result:

`<!DOCTYPE html><title>foobar</title><meta charset=utf-8/ ><meta content="width=device-width,initial-scale=1"name=viewport>`

2.  There is an extra space at the end of the tag here:

```
html_minify('<div class="test"></div>')
'<div class=test ></div>'
```

Should be:

```
html_minify('<div class="test"></div>')
'<div class=test></div>'
```

**Comment by juancarlospaco** [comment]
I remember there was a reason for it, I think some browsers *(IE?, Opera?)* may think that the `class` is `"test>"` which is wrong...
:confused: :thinking:
