### ISSUE TITLE
Not compatible with single-line end-of-line comments.

### ISSUE THREAD

**Issue by jdsutton** [juancarlospaco/css-html-js-minify#59]
Eg:
```
function x() { // todo blah blah
  return 10;
}
```
becomes
`function x() { // todo blah blah return 10; }`

**Comment by rvandyk** [comment]
Do you plan to solve this ?
I'm in a urge

**Comment by jdsutton** [comment]
See https://github.com/juancarlospaco/css-html-js-minify/blob/master/css_html_js_minify/js_minifier.py starting on line 18.

The offending line is line 23.

Maybe instead use a comment-matching regex: https://stackoverflow.com/questions/5989315/regex-for-match-replacing-javascript-comments-both-multiline-and-inline

While the regex finds a match in the code: strip out the match.

**Comment by juancarlospaco** [comment]
Pull Requests welcome...

**Comment by rvandyk** [comment]
It's working fine for me like this 

```
def remove_commented_lines(js):
    """Force remove commented out lines from Javascript."""
    log.debug("Force remove commented out lines from Javascript.")
    result = ""
    for line in js.splitlines():
        line = re.sub(r"/\*.*\*/" ,"" ,line) # (/*COMMENT */)
        line = re.sub(r"//.*","" ,line) # (//COMMENT)
        result += '\n'+line
    return result
```

👍

**Comment by juancarlospaco** [comment]
Fixed by https://github.com/juancarlospaco/css-html-js-minify/commit/a2a79d86213cc723f1f8cc6725afc042504c7ded

Thanks everyone :exclamation:  :smiley_cat::+1:

**Comment by GDI123** [comment]
Hi,
I have one line comment at the end of line in JS file. Trying the last version from MASTER and got an error:

>     line = re.sub(r"/\*.*\*/" ,"" ,line) # (/*COMMENT */)
> NameError: name 're' is not defined

I'm new in python. Can anyone suggest how to fix this?

**Comment by GDI123** [comment]
I've add
`import re`
at the start of js_minifier.py right after
`import logging as log` line and now it works without errors
