### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by warrenspe** [juancarlospaco/css-html-js-minify#65]
Hello,

Would it be at all possible to get a MIT or apache licensed version of this project?

Cheers,

**Comment by juancarlospaco** [comment]
MIT or Apache ?. Decide 1 we will evaluate it.

**Comment by warrenspe** [comment]
MIT would be preferable

**Comment by juancarlospaco** [comment]
[Optional MIT License added.](https://github.com/juancarlospaco/css-html-js-minify/#licence)
