### ISSUE TITLE
Need Mac OsX Native Terminal Screenshot for Readme

### ISSUE THREAD

**Issue by juancarlospaco** [juancarlospaco/css-html-js-minify#7]
- Need Mac OsX Native Terminal Screenshot for Readme *( iTerm2 ?)*.
- 1 JPG or PNG Screenshot of css-html-js-minify running on OsX *(Pull Request, Attach or Link is ok)*.
- Observe the other 2 existing of Linux and Windows as reference.
- Report OsX specific Bugs if found any. 

:octocat:

**Comment by loggerhead** [comment]
Terminal + Zsh
============   
![Terminal](http://s1.momo.moda/2015/04/29/37bc2f75bf1bcfe8450a1a41c200364c.png)

iTerm2 + Zsh
============  
![iTerm](http://s1.momo.moda/2015/04/29/e6b4b2a746ed40e1af829d1fa82daa10.png)

**Comment by juancarlospaco** [comment]
Thank you very much @loggerhead , 
nice to see users on the Os X:grey_exclamation:, even more awesome users that contribute to make it better:exclamation:

Bug Closed; Screenshots added to the front page of the Repo.

:octocat:
