### ISSUE TITLE
Bug setting charset

### ISSUE THREAD

**Issue by giovannigaspar** [juancarlospaco/css-html-js-minify#71]
In the file "css_minifier.py" change the function "add_enconding" to this:

def add_encoding(css):
    """Add @charset 'UTF-8'; if missing."""
    log.debug("Adding encoding declaration if needed.")
    return "@charset \"utf-8\";" + css if "@charset" not in css.lower() else css

I added a Double quote on the return to surround utf-8, otherwise the browser won't compile the css.

**Comment by juancarlospaco** [comment]
Fixed on master.
