### ISSUE TITLE
Overwrite option should not saved as *.min.*

### ISSUE THREAD

**Issue by loggerhead** [juancarlospaco/css-html-js-minify#8]
This is not a *bug*, but a suggestion.

It's a litter strange as I want to overwrite original files but generating *.min.* files instead. And This is not convenient sometimes as the reference of css or js in html are fixed. BTW, you should support *.html files as it is same as *.htm files.

In addition, thanks for your work, it's great!

**Comment by juancarlospaco** [comment]
Hello @loggerhead  :smile_cat: 

Not sure if I understand, are you up-to-date :grey_question:

To Force Overwrite, you can do something like:
```bash
css-html-js-minify.py --overwrite style.css 
```

For example:
```bash
css-html-js-minify.py --overwrite doc_brython.css 

CSS-HTML-JS-Minify.                                                                                                                     
                                                                                                                                        
StandAlone Async single-file cross-platform no-dependencies                                                                             
Unicode-ready Python3-ready Minifier for the Web.                                                                                       
1.0.13                                                                                                                                  
Target is a CSS File.                                                                                                                   
Processing CSS file: /home/juan/code/css-html-js-minify/doc_brython.css.                                                                
Compressing CSS... 
Removing all Comments. 
Alphabetically Sorting and Grouping all CSS Properties. 
Removing unnecessary Quotes on selectors of CSS classes. 
Condensing all unnecessary white spaces. 
Removing quotes from url. 
Condensing extended named color values. 
Condensing font weights on values. 
Removing all unnecessary white spaces. 
Condensing standard named color values. 
Removing all unnecessary semicolons. 
Condensing all zeroes on values. 
Condensing all multidimensional zeroes on values. 
Condensing all floating point values. 
Converting all rgba to hexadecimal color values. 
Condensing all hexadecimal color values. 
Condense borders values. 
Condensing all unnecessary multiple adjacent semicolons. 
Adding encoding declaration if needed. 
Finished compressing CSS !. 
Prepending '.CSS' Prefix to /home/juan/code/css-html-js-minify/doc_brython.css. 
-------------------------------------------------------------------------------- 
Files Processed: /home/juan/code/css-html-js-minify/doc_brython.css. 
Number of Files Processed: 1. 
Total Maximum RAM Memory used: ~60 MegaBytes. 
Total Processing Time: 0:00:00.023621. 
juan@z:~/code/css-html-js-minify$ 
```

Check the version with:
```bash
css-html-js-minify.py --version
1.0.13

juan@z:~/code/css-html-js-minify$
```

Get more Help with:
```bash
css-html-js-minify.py --help   

usage: css-html-js-minify.py [-h] [--version] [--wrap] [--prefix PREFIX]
                             [--timestamp] [--quiet] [--obfuscate]
                             [--checkupdates] [--tests] [--hash] [--gzip]
                             [--comments] [--overwrite] [--after AFTER]
                             [--before BEFORE] [--watch] [--_42]
                             fullpath

CSS-HTML-JS-Minify. StandAlone Async single-file cross-platform no-
dependencies Unicode-ready Python3-ready Minifier for the Web.

positional arguments:
  fullpath         Full path to local file or folder.

optional arguments:
  -h, --help       show this help message and exit
  --version        show programs version number and exit
  --wrap           Wrap output to ~80 chars per line, CSS only.
  --prefix PREFIX  Prefix string to prepend on output filenames.
  --timestamp      Add a Time Stamp on all CSS/JS output files.
  --quiet          Quiet, Silent, force disable all logging.
  --obfuscate      Obfuscate Javascript. JS only. (Recommended).
  --checkupdates   Check for updates from internet while running.
  --tests          Run all built-in Unit Tests, report and exit.
  --hash           Add SHA1 HEX-Digest 11chars Hash to Filenames.
  --gzip           GZIP Minified files as '*.gz', CSS/JS only.
  --comments       Keep comments, CSS/HTML only (Not Recommended)
  --overwrite      Force overwrite all in-place (Not Recommended)
  --after AFTER    Command to execute after run (Experimental).
  --before BEFORE  Command to execute before run (Experimental).
  --watch          Re-Compress if file changes (Experimental).
  --_42

CSS-HTML-JS-Minify: Takes a file or folder full path string and process all
CSS/HTML/JS found. If argument is not file/folder will fail. Check Updates
works on Python3. Std-In to Std-Out is deprecated since it may fail with
unicode characters. SHA1 HEX-Digest 11 Chars Hash on Filenames is used for
Server Cache. CSS Properties are Alpha-Sorted, to help spot cloned ones,
Selectors not. Watch works for whole folders, with minimum of ~60 Secs between
runs.
juan@z:~/code/css-html-js-minify$
```

- If you consider that the parameter `--help` can be improved, add something, something is hard to understand, please comment what do you want it to have explained :grey_question: 
- If the Bug still reproduces, please paste the whole Terminal text content.

:octopus:

**Comment by loggerhead** [comment]
1. Yes. I am up-to-date (1.0.13).
2. ``css-html-js-minify.py --overwrite index.html`` will produce ``index.htmll`` instead of ``index.html``.
    
    ![](http://s1.momo.moda/2015/04/30/06997f04a7db92466a2baa6ebc8b872d.png)

3. ``css-html-js-minify.py .`` not work to ``.html`` suffix.
    
    ![](http://s1.momo.moda/2015/04/30/26408ffa703a72e8ac0117e74ad46f33.png)

**Comment by loggerhead** [comment]
They are not bugs, but not convenient to use...

**Comment by juancarlospaco** [comment]
*Smeels like Bug...*

Lets see, the `css-html-js-minify.py .` it does support the `--overwrite` for whole folders too, 
is what should be used for overwrite while processing whole folders.

Let me check the `.HTMLL` should not be doing that... :crying_cat_face: 

:bug:

**Comment by juancarlospaco** [comment]
The problem is here:

- How to differentiate by default **Human/Development HTML** and the **Minified/Production HTML**:question:
- Everyone uses `*.min.js` and `*.min.css` for Prod, and `*.js` and `*.css` for Hacking.
- Everyone uses `*.html` for Prod on Servers, Frameworks, etc etc.
- We can not depend on OS-Specific Meta Properties/Attributes *(Hidden file, etc etc)*.
- This humble project can not change that behaviour, but we need something similar for HTML.
- `*.htm` is just another standard extension of HTML.
- We can safely use that to differentiate the HTMLs.
- css-html-js-minify provides the `--after` and `--before` where you can use something like https://github.com/juancarlospaco/css-html-js-minify#migration
- That creates something similar to the `*.min.js` and `*.min.css`.
- You double click a `*.htm` and still opens with Editor/IDE/etc.
- You end up with `file.html` Minified and `file.htm` for friendly reading and hacking.

:octocat:

**Comment by juancarlospaco** [comment]
`css-html-js-minify.py --overwrite index.html` will produce `index.html` instead of `index.htmll`

Seems like its working Ok, Fix is on Repo, feel free to keep commenting ideas, I am closing this for now...
