### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by skolsuper** [juancarlospaco/css-html-js-minify#9]
This is not an issue, but a question: due to the following:

```
The GNU General Public License does not permit incorporating your program
into proprietary programs.
```

I am not allowed to use this script in a proprietary, django-based website right?

**Comment by juancarlospaco** [comment]
- http://opensource.org/licenses/LGPL-3.0

But **L**GPL does AFAIK :smile_cat: so... Yes, you can.

**Comment by skolsuper** [comment]
Awesome, thanks.  I only opened the LICENSE file before, which is GPL, just now I checked the readme which states GPL && LGPL.  Out of interest, why use both?  Does and-ing them together mean only the lesser restrictions apply?

**Comment by juancarlospaco** [comment]
So thats a Bug, LGPL should ne on the Repo,will Fix it soon...  :astonished:

**Comment by juancarlospaco** [comment]
LGPL is on the Repo. :smiley_cat:

**Comment by skolsuper** [comment]
:thumbsup:
